version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.5
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.1
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: svelte
    versions:
    - 3.32.0
    - 3.32.1
    - 3.32.2
    - 3.34.0
    - 3.35.0
    - 3.36.0
  - dependency-name: clipboard
    versions:
    - 2.0.7
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 99
